
  create table users (
  user_id bigint generated by default as identity,
  user_name varchar(255),
  first_name varchar(255),
  last_name varchar(255),
  primary key (user_id));

  create table followers (
	followed_user_id bigint not null,
	follower_user_id bigint not null
  );
  
  create table tweets (
	tweet_id bigint generated by default as identity,
	text varchar(255),
	attachment_file_name varchar(255),
	user_id bigint not null,
	primary key (tweet_id)
  );
  
  create table replies (
	reply_id bigint generated by default as identity,
	text varchar(255),
	attachment_file_name varchar(255),
	user_id bigint not null,
	tweet_id bigint not null,
	primary key (reply_id)
  );  
  